# Generated by Django 4.2.15 on 2024-09-16 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kaizen', '0003_rename_protien_intake_runningmacro_protein_intake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_protein_intake', models.FloatField(default=0)),
                ('total_carb_intake', models.FloatField(default=0)),
                ('total_fat_intake', models.FloatField(default=0)),
                ('total_tdee_intake', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
