# Generated by Django 4.2.15 on 2024-09-29 03:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Kaizen', '0004_dailytotals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyTotals',
            new_name='DailyTotal',
        ),
    ]
