# Generated by Django 4.2.15 on 2024-09-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0005_rename_dailytotals_dailytotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
    ]
