# Generated by Django 4.2.15 on 2024-10-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kaizen', '0008_alter_meal_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
